---

- name: install flatpak
  apt:
    name:
      - flatpak
    update_cache: yes
    state: present

- name: Getting process IDs of udev process (not running in docker container on CI build)
  ansible.builtin.command: ps -C systemd-udevd
  register: ps_udevd
  changed_when: false
  failed_when: ps_udevd.stderr != ""

- name: debug reistered var
  ansible.builtin.command: /lib/systemd/systemd-udevd --daemon
  when: ps_udevd.rc != 0

- name: copy udev rules for mobsya
  copy:
    src: 99-mobsya.rules
    dest: /etc/udev/rules.d/99-mobsya.rules
    mode: 0644
  register: mobsya_rules

- name: update udev rules
  command: udevadm control --reload-rules
  when: mobsya_rules.changed
 
- name: add flatpak repo 
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install aseba distribution
  flatpak:
    name: org.mobsya.ThymioSuite
    state: present

- name: download aseba logo
  copy:
    src: aseba.png
    dest: '/usr/share/pixmaps/aseba.png'
    mode: 0644

- name: create desktop Entry
  copy:
    src: aseba.desktop
    dest: /usr/share/applications/
    mode: 0644
