---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -x 503
platforms:
  - name: debian10
    image: debian:buster
    volumes:
      - /dev:/dev
provisioner:
  name: ansible
scenario:
  name: default
  converge_sequence:
    - prepare
    - converge
verifier:
  name: testinfra
